# 1. How to create basic arrays

To create an array of a specified number of zeros we use:

In [ ]:
import numpy as np # Run this cell or the numpy commands won't run

In [ ]:
n = 5
array_of_zeros = np.zeros(n)
print(array_of_zeros)

[0. 0. 0. 0. 0.]


---

## Exercise 1.1

In the cell below create a numpy array that is filled with 50 zeros. Then print it.

---

To create an array of a specified number of ones we use:

In [ ]:
m = 6
array_of_ones = np.ones(m)
print(array_of_ones)

[1. 1. 1. 1. 1. 1.]


---

## Exercise 1.2

In the cell below create a numpy array that is filled with 65 ones. Then print it.

---

To create an array of a specified number of some other value we use:

In [ ]:
r = 7
value = 2.
array_of_same_val = np.full(r, value)
print(array_of_same_val)

[2. 2. 2. 2. 2. 2. 2.]


Note that the first argument of ``np.full`` is its shape, and the second argument is the value that we wish to fill.

---

## Exercise 1.3

In the cell below create a numpy array that is filled with 40 occurences of a string "I'm only a clone".

---

### Ranging values

To create an array with elements to match the ``range`` function, so that we specify the start, stop and the step we use:

``np.arange(start, stop, step)``


In [ ]:
start = 5
stop = 10
step = 2
print(np.arange(start, stop, step))

[5 7 9]


---

## Exercise 1.4

In the cell below create an array of consecutive 50 integers, starting from 100 (ie, [100,101,102, 103, ...]. Use the np.arange function, not range. Then print the resulting array.  

## Exercise 1.5

In the cell below create an array of all even integers in the interval $[0, 100]$. Then print the resulting array.

---

### Linear space
To create an array with values that are spaced linearly in a specific interval, we use:

``np.linspace(start_int, end_int, num_points)``

In [ ]:
start_int = 0
end_int = 10
num_points = 5
print(np.linspace(start_int, end_int, num_points))

[ 0.   2.5  5.   7.5 10. ]


---

## Exercise 1.6

In the cell below create an array of 100 equally spaced points from an interval $[0, 1]$. First find the start of the interval, that the end point of the interval, and then specify the number of equally spaced points.

---

## Differences and similarities between ``arange`` and ``linspace``.
Note the difference and similarities between ``np.arange`` and ``np.linspace``.

With ``np.arange`` similarly to ``range`` function the last value is ``stop - step``, while in the ``np.linspace`` the last value is ``end_int``.

Unlike ``range`` ``np.arange`` allows the step to be a float; in ``range`` only ``ints`` are accepted for the step.

``np.linspace`` finds the right step automatically, based on the number of points. In ``np.arange`` we specify the step that then determines the number of points.

#### Caution

In some cases it is recommended to use ``np.linspace`` over ``np.arange``. With steps being floats ``np.arange`` sometimes returns unexpected outputs due to a floating point error. See the example below:

In [ ]:
np.arange(1.0, 1.3, 0.1)

array([1. , 1.1, 1.2, 1.3])

Due to a floating point error it includes 1.3, and does not follow the rule of the last element of an array being ``stop - step``.

This issue can occur only if the step is a float.


**NOTE** both `np.linspace` and `np.arange` are very useful tools where "iterating" (or looping) over a range of values. Think again about the differences between both and consider which one is more appropriate for what you are doing!