# Iterating over an numpy array - SOLVED

To iterate over the rows of a 2d numpy array we use:

In [ ]:
import numpy as np #Run this cell or none of the np commands will work

In [ ]:
two_dim_array = np.array([[1.4, 2.3, 5.3],[1.5, 3.2, 6.7]])

for row in two_dim_array:
    print("######################")
    print(f"the row is {row}")

######################
the row is [1.4 2.3 5.3]
######################
the row is [1.5 3.2 6.7]


## Exercise 4.1

Please evaluate the cell below.

In [ ]:
two_dim_array_rand =  np.random.uniform(0, 100, size = (5, 10))

In the cell below iterate over each row of the above 2d numpy array, and print the (elementwise) square root of each row.

In [ ]:
for row in two_dim_array_rand:
  sdev = np.std(row)
  print("######################")
  print(f"the square root of the row {row} is {sdev}.")

######################
the square root of the row [83.18831117 52.47275489  2.45411385  6.83428588 91.90321903 12.40267797
 36.0111949  24.08914145 73.7281718  42.31896235] is 30.55080535248819.
######################
the square root of the row [32.65897531 18.79780814 33.04346565 83.34098514 67.33516714 38.79838185
 14.14683332 69.3261518  34.14000727 96.94158866] is 26.833303564163973.
######################
the square root of the row [ 3.2702164  43.35002869 22.12230309 86.46795707 38.41941469 34.3707251
 91.54505265 20.03942776 80.74434313 67.46210212] is 29.278352447020886.
######################
the square root of the row [87.76458264 62.64231177 47.07796805 93.56074851 98.72618016 31.88377881
 33.53280247 84.77476322 22.71449012 56.81327062] is 26.529364785882258.
######################
the square root of the row [ 2.33253354 59.2443077  22.42631401  9.43871419  2.19546723 47.58592949
 61.92071672 99.94834654 11.99618779 98.79790855] is 35.789983002572626.


To iterate *all* elements of the array we can use the ``flat`` function:

In [ ]:
for element in two_dim_array.flat:
    print("######################")
    print(f"the element is {element}")

######################
the element is 1.4
######################
the element is 2.3
######################
the element is 5.3
######################
the element is 1.5
######################
the element is 3.2
######################
the element is 6.7


but perhaps it is easier to understand this if we loop over the rows *and then* loop over the columns within this loop (so using nested looping as we introduced in the third week!)

In [ ]:
for row in two_dim_array:
    for element in row:
        print("######################")
        print(f"the element is {element}")


######################
the element is 1.4
######################
the element is 2.3
######################
the element is 5.3
######################
the element is 1.5
######################
the element is 3.2
######################
the element is 6.7


## Exercise 4.2

Please evaluate the cell below:

In [ ]:
three_dim_array =  np.random.uniform(0, 10, size = (5, 4, 2))
print(three_dim_array)

[[[1.13169973 9.76905622]
  [9.0102443  8.6560646 ]
  [0.3852     4.33477275]
  [7.0685131  6.79397214]]

 [[0.01022187 3.52963969]
  [2.81035945 6.98988701]
  [6.91189417 5.77114685]
  [2.86017778 8.73165679]]

 [[9.35091606 9.88628105]
  [5.02850667 9.02716249]
  [1.66208526 7.17957221]
  [2.47400101 8.75195124]]

 [[6.28325582 2.94194586]
  [0.76869755 4.77282471]
  [7.17403101 7.25206593]
  [5.63653023 8.08791847]]

 [[0.10231449 8.4750223 ]
  [1.33082937 5.1385074 ]
  [6.46399994 2.76536177]
  [5.06544867 4.07532158]]]


In the cell below iterate over each element of the array, and print the square of each element. (Note, that in this three dimensional array you would need *three* for loops if using nested loops. Using `flat` would certainly be easier here, but perhaps not so clear)

In [ ]:
for row in three_dim_array:
  for column in row:
    for val in column:
      print(val)

1.131699734627022
9.769056219280351
9.010244303622674
8.65606460163018
0.3852000026475866
4.334772752003113
7.068513095724102
6.793972142514589
0.010221873682785265
3.529639691730443
2.8103594544683084
6.989887013030379
6.911894170645569
5.7711468488345865
2.8601777848344256
8.731656794325866
9.35091606155366
9.886281049016963
5.028506669629396
9.027162491117863
1.662085260204591
7.179572210160879
2.474001010579575
8.751951243606618
6.283255821802555
2.941945862040518
0.768697547234265
4.772824706024467
7.174031008660263
7.252065925112358
5.636530226346615
8.087918471772271
0.10231449351210231
8.475022303904256
1.330829366066535
5.138507403882433
6.463999942788828
2.765361769538993
5.065448672210442
4.075321576171756
