# Part 2: viewing data

This workbook requires you to load the `` titanic`` and ``avocado`` datasets. You will also need to run the following block of code to import ``numpy`` and ``pandas``:

In [4]:
import pandas as pd
import numpy as np

Load the ``titanic`` and ``avocado`` data sets as a ``pandas`` dataframes in the code block below:

In [20]:
# Code to load the Titanic and avocado data sets
df_titanic = pd.read_excel("titanic.xlsx")
df_avocado = pd.read_excel("avocado.xlsx")

## Exploring datasets in more detail

Let's come back to our ``titanic`` example. We can access the index of the DataFrame as follows:


In [21]:
df_titanic.index

RangeIndex(start=0, stop=891, step=1)

By default it is a pandas RangeIndex type, it works similarly to ``range`` it starts at 0, the last entry is stop - 1, the step is 1.

We may use different type of indexing, but for now we are going to use the default one.

How about displaying all the column names of our Data Frame?
We do it as follows:

In [22]:
df_titanic.columns

Index(['PassengerId', 'Name', 'Sex', 'Age', 'Ticket', 'Fare', 'Cabin',
       'Survived'],
      dtype='object')

This type can be treated as a list or numpy array, we can call its elements via an index.

In [8]:
df_titanic.columns[0], df_titanic.columns[-1]

('PassengerId', 'Survived')

We already know how to view values of a particular column, e.g.

``df_titanic["Survived"]``

If the name of the column does not contain spaces we can also view the values by

In [9]:
df_titanic.Survived

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

If we wish to get numpy array from the pd.Series we use ``your_pd_series.values``:

In [10]:
df_titanic.Survived.values

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

Pandas is very compatible with numpy, in fact, we can simply convert a DataFrame to a numpy array.

In [11]:
titanic_np_array = df_titanic.to_numpy()
print(titanic_np_array)

[[1 'Braund, Mr. Owen Harris' 'male' ... 7.25 nan 0]
 [2 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)' 'female' ...
  71.2833 'C85' 1]
 [3 'Heikkinen, Miss. Laina' 'female' ... 7.925 nan 1]
 ...
 [889 'Johnston, Miss. Catherine Helen "Carrie"' 'female' ... 23.45 nan 0]
 [890 'Behr, Mr. Karl Howell' 'male' ... 30.0 'C148' 1]
 [891 'Dooley, Mr. Patrick' 'male' ... 7.75 nan 0]]


We can also get a quick statistic summary of our data. This is done via:

In [12]:
df_titanic.describe()

PassengerId         Age        Fare    Survived
count   891.000000  714.000000  891.000000  891.000000
mean    446.000000   29.699118   32.204208    0.383838
std     257.353842   14.526497   49.693429    0.486592
min       1.000000    0.420000    0.000000    0.000000
25%     223.500000   20.125000    7.910400    0.000000
50%     446.000000   28.000000   14.454200    0.000000
75%     668.500000   38.000000   31.000000    1.000000
max     891.000000   80.000000  512.329200    1.000000

Note that for pandas ``displaying`` produces nicer outputs than ``printing``

In [13]:
print(df_titanic.describe())

       PassengerId         Age        Fare    Survived
count   891.000000  714.000000  891.000000  891.000000
mean    446.000000   29.699118   32.204208    0.383838
std     257.353842   14.526497   49.693429    0.486592
min       1.000000    0.420000    0.000000    0.000000
25%     223.500000   20.125000    7.910400    0.000000
50%     446.000000   28.000000   14.454200    0.000000
75%     668.500000   38.000000   31.000000    1.000000
max     891.000000   80.000000  512.329200    1.000000


Displaying can be also achieved through display command as follows:

In [14]:
display(df_titanic.describe())

PassengerId         Age        Fare    Survived
count   891.000000  714.000000  891.000000  891.000000
mean    446.000000   29.699118   32.204208    0.383838
std     257.353842   14.526497   49.693429    0.486592
min       1.000000    0.420000    0.000000    0.000000
25%     223.500000   20.125000    7.910400    0.000000
50%     446.000000   28.000000   14.454200    0.000000
75%     668.500000   38.000000   31.000000    1.000000
max     891.000000   80.000000  512.329200    1.000000

Note that the above stats are only for the numerical columns.

### Exercise 2.1

With the avocado data frame from Exercise 0.1:

Please display its columns.

In [19]:
print(df_avocado.columns)

Index([        'Date', 'AveragePrice', 'Total Volume',           4046,
                 4225,           4770,   'Total Bags',   'Small Bags',
         'Large Bags',  'XLarge Bags',         'type',         'year',
             'region'],
      dtype='object')


Display the stats of this data frame:

In [26]:
display(df_avocado.describe())

AveragePrice  Total Volume          4046          4225          4770  \
count  18249.000000  1.824900e+04  1.824900e+04  1.824900e+04  1.824900e+04   
mean       1.405978  8.506440e+05  2.930084e+05  2.951546e+05  2.283974e+04   
std        0.402677  3.453545e+06  1.264989e+06  1.204120e+06  1.074641e+05   
min        0.440000  8.456000e+01  0.000000e+00  0.000000e+00  0.000000e+00   
25%        1.100000  1.083858e+04  8.540700e+02  3.008780e+03  0.000000e+00   
50%        1.370000  1.073768e+05  8.645300e+03  2.906102e+04  1.849900e+02   
75%        1.660000  4.329623e+05  1.110202e+05  1.502069e+05  6.243420e+03   
max        3.250000  6.250565e+07  2.274362e+07  2.047057e+07  2.546439e+06   

         Total Bags    Small Bags    Large Bags    XLarge Bags          year  
count  1.824900e+04  1.824900e+04  1.824900e+04   18249.000000  18249.000000  
mean   2.396392e+05  1.821947e+05  5.433809e+04    3106.426507   2016.147899  
std    9.862424e+05  7.461785e+05  2.439660e+05   17692.894652      0.939938  
min    0.000000e+00  0.000000e+00  0.000000e+00       0.000000   2015.000000  
25%    5.088640e+03  2.849420e+03  1.274700e+02       0.000000   2015.000000  
50%    3.974383e+04  2.636282e+04  2.647710e+03       0.000000   2016.000000  
75%    1.107834e+05  8.333767e+04  2.202925e+04     132.500000   2017.000000  
max    1.937313e+07  1.338459e+07  5.719097e+06  551693.650000   2018.000000

Display all the entries of this data frame in the column ``Total Bags``.

In [34]:
df_avocado.columns
display(df_avocado['Total Bags'])

0         8696.87
1         9505.56
2         8145.35
3         5811.16
4         6183.95
           ...   
18244    13498.67
18245     9264.84
18246     9394.11
18247    10969.54
18248    12014.15
Name: Total Bags, Length: 18249, dtype: float64

Convert your data frame to a numpy array and then print it.

In [36]:
avocado_np_array = df_avocado.to_numpy()

print(avocado_np_array)

[[Timestamp('2015-12-27 00:00:00') 1.33 64236.62 ... 'conventional' 2015
  'Albany']
 [Timestamp('2015-12-20 00:00:00') 1.35 54876.98 ... 'conventional' 2015
  'Albany']
 [Timestamp('2015-12-13 00:00:00') 0.93 118220.22 ... 'conventional' 2015
  'Albany']
 ...
 [Timestamp('2018-01-21 00:00:00') 1.87 13766.76 ... 'organic' 2018
  'WestTexNewMexico']
 [Timestamp('2018-01-14 00:00:00') 1.93 16205.22 ... 'organic' 2018
  'WestTexNewMexico']
 [Timestamp('2018-01-07 00:00:00') 1.62 17489.58 ... 'organic' 2018
  'WestTexNewMexico']]


### Transposing your data

You may have heard about transposing operation. In matrices, a transpose swaps the rows with columns. This operation make sense with numpy arrays and Data Frames as well.

In [37]:
my_matrix = np.array([[1, 2], [3, 4]])
print(f"Original matrix \n {my_matrix}")
print(f"Transposed matrix \n {my_matrix.T}")

Original matrix 
 [[1 2]
 [3 4]]
Transposed matrix 
 [[1 3]
 [2 4]]


In [38]:
df_titanic_t = df_titanic.T
df_titanic_t

0    \
PassengerId                        1   
Name         Braund, Mr. Owen Harris   
Sex                             male   
Age                             22.0   
Ticket                     A/5 21171   
Fare                            7.25   
Cabin                            NaN   
Survived                           0   

                                                           1    \
PassengerId                                                  2   
Name         Cumings, Mrs. John Bradley (Florence Briggs Th...   
Sex                                                     female   
Age                                                       38.0   
Ticket                                                PC 17599   
Fare                                                   71.2833   
Cabin                                                      C85   
Survived                                                     1   

                                2    \
PassengerId                       3   
Name         Heikkinen, Miss. Laina   
Sex                          female   
Age                            26.0   
Ticket             STON/O2. 3101282   
Fare                          7.925   
Cabin                           NaN   
Survived                          1   

                                                      3    \
PassengerId                                             4   
Name         Futrelle, Mrs. Jacques Heath (Lily May Peel)   
Sex                                                female   
Age                                                  35.0   
Ticket                                             113803   
Fare                                                 53.1   
Cabin                                                C123   
Survived                                                1   

                                  4                 5    \
PassengerId                         5                 6   
Name         Allen, Mr. William Henry  Moran, Mr. James   
Sex                              male              male   
Age                              35.0               NaN   
Ticket                         373450            330877   
Fare                             8.05            8.4583   
Cabin                             NaN               NaN   
Survived                            0                 0   

                                 6                               7    \
PassengerId                        7                               8   
Name         McCarthy, Mr. Timothy J  Palsson, Master. Gosta Leonard   
Sex                             male                            male   
Age                             54.0                             2.0   
Ticket                         17463                          349909   
Fare                         51.8625                          21.075   
Cabin                            E46                             NaN   
Survived                           0                               0   

                                                           8    \
PassengerId                                                  9   
Name         Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   
Sex                                                     female   
Age                                                       27.0   
Ticket                                                  347742   
Fare                                                   11.1333   
Cabin                                                      NaN   
Survived                                                     1   

                                             9    ...                 881  \
PassengerId                                   10  ...                 882   
Name         Nasser, Mrs. Nicholas (Adele Achem)  ...  Markun, Mr. Johann   
Sex                                       female  ...                male   
Age                                         14.0  ...                33.0   
Ticket        

With this particular example it is not the best thing to do. However, we have got an interesting data frame. Let's spend some time on it.

### Exercise 2.2

Display the index of the above transposed titanic DataFrame.

In [39]:
df_titanic_t.index

Index(['PassengerId', 'Name', 'Sex', 'Age', 'Ticket', 'Fare', 'Cabin',
       'Survived'],
      dtype='object')

Note that it starts with an index but its elements can be accessed as lists.